name: Build and Publish Library with Maven

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@a00c5981b61673992de3cde9f95f1f8be30ca0eb # v1.37.3
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      slack-channel: '#panda-ci'
      slack-bot-name: "GitHub Actions"
      slack-bot-icon: ':panda_face:'