name: Release from [release] commits (Maven)

on:
  push:
    branches: [ "main" ]  # endre ved behov

permissions:
  contents: write  # kreves for å pushe tag og opprette release
  packages: read

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip actions]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Setup settings.xml for GitHub Packages
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>with-github</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/statens-pensjonskasse/tidsserie</url>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/statens-pensjonskasse/tidsserie</url>
                  </pluginRepository>
                </pluginRepositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>with-github</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Build with Maven
        run: mvn -B verify

      - name: Collect build files
        run: |
          mkdir -p dist
          shopt -s globstar || true
          cp **/target/* dist/ 2>/dev/null

      - name: Upload build artifacts (snapshot)
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-build
          path: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
