name: Build and Publish Library with Maven
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@c5c7da4d814f7b5ac75358e662cf27970012d682 # v1.3.2
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: 21

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4 #v4.2.2
      - name: report to slack
        uses: statens-pensjonskasse/gal-components/send-slack-notification@58ba8cf4dbc7e0e58a9e4ae7bf38b868f1be4626 # v0.1.0
        with:
          channel: '#panda-ci'
          status: ${{ needs.build.result }}
          message: ${{ env.commit_msg }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
